#sample product details
Product.create!([{ name: 'Laptop',
	description: 'Electronic device',
	images: 'Not avilble',
	launch_date: Date.today,
	price: 77000.00,
	currency: 'INR',
	active: true },
	{ name: 'Mobile',
	description: 'Electronic device',
	images: 'Not avilble',
	launch_date: Date.today,
	price: 44000.00,
	currency: 'INR',
	active: true },
	{ name: 'Reading Table',
	description: 'Furniture',
	images: 'Not avilble',
	launch_date: Date.today,
	price: 7000.00,
	currency: 'INR',
	active: true },
	{ name: 'Wallframe',
	description: 'Home improvements',
	images: 'Not avilble',
	launch_date: Date.today,
	price: 450.00,
	currency: 'INR',
	active: true },
	{ name: 'Formal Shoes',
	description: 'Footware',
	images: 'Not avilble',
	launch_date: Date.today,
	price: 1999.00,
	currency: 'INR',
	active: true }])

#sample user data with admin details
User.create!([{name: 'Administrator',
	email: 'admin_7@gmail.com',
	address: 'New York',
	country: 'USA',
	timezone: 'America/Los_Angeles',
	password: '123456',
	admin: true},
	{name: 'Justin',
	email: 'Justin@gmail.com',
	address: 'California',
	country: 'USA',
	timezone: 'America/Los_Angeles',
	password: '123456'},
	{name: 'Mike',
	email: 'Mike.s@gmail.com',
	address: 'brewenski',
	country: 'Canada',
	timezone: 'Canada/Central',
	password: '123456'},
	{name: 'Jhon',
	email: 'Jhon@gmail.com',
	address: 'Catter',
	country: 'Africa',
	timezone: 'Africa/Cairo',
	password: '123456'},
	{name: 'Subhash',
	email: 'subhash@gmail.com',
	address: 'Delhi',
	country: 'India',
	timezone: 'Asia/Kolkata',
	password: '123456'},
	{name: 'Hashmi',
	email: 'Hashmi@gmail.com',
	address: 'azar',
	country: 'Singapore',
	timezone: 'Asia/Singapore',
	password: '123456'}])
